package packet;
import core.*;import java.util.ArrayList;import java.util.Collections;import java.util.HashSet;import java.util.List;import java.util.Set;
public final class DnsMessage{
 private final int id;private final int flags;private final List<DnsQuestion> questions;private final List<DnsRecord> answers;
 public DnsMessage(int id,int flags,List<DnsQuestion> questions,List<DnsRecord> answers){this.id=id;this.flags=flags;this.questions=questions;this.answers=answers;}
 public static ParseResult<DnsMessage> parse(byte[] data){Diagnostics d=new Diagnostics();if(data==null||data.length<12)return ParseResult.failure("dns.truncated","DNS header truncated");int id=Endian.u16be(data,0);int flags=Endian.u16be(data,2);int qd=Endian.u16be(data,4);int an=Endian.u16be(data,6);int off=12;List<DnsQuestion> qs=new ArrayList<>();List<DnsRecord> ans=new ArrayList<>();for(int i=0;i<qd&&off<data.length;i++){NameResult nr=readName(data,off,new HashSet<>(),d);off=nr.next;if(off+4>data.length){d.medium("dns.question.truncated","question fields truncated");break;}qs.add(new DnsQuestion(nr.name,Endian.u16be(data,off),Endian.u16be(data,off+2)));off+=4;}for(int i=0;i<an&&off<data.length;i++){NameResult nr=readName(data,off,new HashSet<>(),d);off=nr.next;if(off+10>data.length){d.medium("dns.rr.truncated","record fields truncated");break;}int type=Endian.u16be(data,off);int cls=Endian.u16be(data,off+2);long ttl=Endian.u32be(data,off+4);int len=Endian.u16be(data,off+8);off+=10;if(off+len>data.length){d.medium("dns.rdata.truncated","record rdata truncated");len=Math.max(0,data.length-off);}ans.add(new DnsRecord(nr.name,type,cls,ttl,SafeSlice.copy(data,off,len)));off+=len;}return ParseResult.of(new DnsMessage(id,flags,qs,ans),d);}
 private static final class NameResult{String name;int next;NameResult(String n,int x){name=n;next=x;}}
 private static NameResult readName(byte[] data,int off,Set<Integer> seen,Diagnostics d){StringBuilder sb=new StringBuilder();int pos=off;int consumed=-1;while(pos<data.length){if(!seen.add(pos)){d.medium("dns.name.loop","compression pointer loop");break;}int len=data[pos]&255;if(len==0){pos++;break;}if((len&0xc0)==0xc0){if(pos+1>=data.length){d.medium("dns.name.pointer","truncated compression pointer");pos=data.length;break;}int ptr=((len&0x3f)<<8)|(data[pos+1]&255);if(consumed<0)consumed=pos+2;pos=ptr;continue;}if(len>63){d.medium("dns.name.label","label length exceeds DNS limit");break;}pos++;if(pos+len>data.length){d.medium("dns.name.truncated","label truncated");pos=data.length;break;}if(sb.length()>0)sb.append('.');for(int i=0;i<len;i++){int c=data[pos+i]&255;sb.append((c>=32&&c<127)?(char)c:'?');}pos+=len;}return new NameResult(sb.toString().toLowerCase(java.util.Locale.ROOT),consumed>=0?consumed:pos);}
 public int id(){return id;}public int flags(){return flags;}public boolean response(){return(flags&0x8000)!=0;}public List<DnsQuestion> questions(){return Collections.unmodifiableList(questions);}public List<DnsRecord> answers(){return Collections.unmodifiableList(answers);}
}
